### ISSUE TITLE
Breaks if children change happens too quickly

### ISSUE THREAD

**Issue by aaronbeall** [chipit24/fade-props#1]
I have some code like this:

```
const children = loaded ? <Buttons key="buttons" /> : <Loader key="loader" />;
<FadeProps animationLength={500} children={children} />
```

When it switches from `loaded=true` to `loaded=false` then back to `loaded=true` too quickly (less than the animation time, roughly) the content fades out, but nothing fades in.

In this recording below when I click "Lets Go" it sets `loaded=false` which fades out the button and when the error "Name already taken" appears it sets `loaded=true` (before the button has finished fading out) but the button never fades back in (nor does the loader ever show up):

![fade out no fade in](http://g.recordit.co/gg94oepZrH.gif)

I need the buttons to either fade back in after they fade out, or (preferably) interrupt the fade out and fade back to 100% opacity.

For reference, if the change happens with enough time for the fades to complete it looks like this:

![fade out and fade in](http://g.recordit.co/JLBnPjyIBv.gif)

**Comment by aaronbeall** [comment]
@chipit24 Any update on this? Would you accept a PR?

**Comment by chipit24** [comment]
Haven't had time to work on it yet 😔 I will definitely accept a PR 😀 Otherwise I'll try to get to it this week!

**Comment by chipit24** [comment]
@aaronbeall This should now be fixed in the latest release, let me know if you still have issues.
