### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by d4rky-pl** [chipit24/fade-props#3]
Right now the package has hard dependency on specific version of React, meaning it fetches it's own copy, causing compatibility issues. Please consider adding version ranges instead.

**Comment by chipit24** [comment]
Thanks @d4rky-pl! This has been on my radar and I'll get an update in soon to add react to peerDependencies and remove the hard dependency 🙈

**Comment by chipit24** [comment]
This should be fixed now. Let me know if there are any other issues.
